add: wishlist
ravi300601/EasyCart pull request #1
Opened 2024-09-17 09:29 UTC by user-64bit

2024-09-17 09:36 UTC, ravi300601 commented on src/components/userProfile/userProfile.jsx
> +    },
remove extra space

2024-09-17 09:37 UTC, user-64bit commented on src/components/userProfile/userProfile.jsx
> +    },
Done :+1:

2024-09-17 10:45 UTC, ravi300601 requested changes

2024-09-17 10:45 UTC, ravi300601 commented on src/components/userProfile/userProfile.jsx
> +          </form>
Don't need to implement this function as this is already available for use

2024-09-17 10:45 UTC, ravi300601 commented on src/pages/wishlist/wishlist.jsx
> +                                    <td>No Items here..</td>
display statement like
- "Oops! Your wishlist looks empty. Browse and add items to save for later."
- "You haven't added any items to your wishlist. Discover something special today!"
- "Nothing here yet! Explore our collection and add items to your wishlist."

2024-09-17 10:45 UTC, ravi300601 commented on src/pages/wishlist/wishlist.jsx
> +
remove extra line

2024-09-17 11:49 UTC, 0xuser64bit commented on src/components/userProfile/userProfile.jsx
> +          </form>
Done :+1: 
.thanks

2024-09-18 10:20 UTC, ravi300601 approved these changes

2024-09-18 10:20 UTC, ravi300601 commented
LGTM :rocket: 
Thanks for your work.

2024-09-18 10:21 UTC, merged